---
### waiting for helm updated version
#- name: get /etc/values.yaml
#  template:
#    src: templates/k8s/values.yaml
#    dest: /etc/values.yaml 
#
#- name: create tts_cache pod
#  command: helm repo add ms https://dodas-ts.github.io/docker-img_cms/ && helm update && helm install -f /etc/values.yaml cms/

- name: compile squid pod config
  template:
    src: templates/k8s/squid.json
    dest: /etc/squid.json

- name: compile squid service config
  template:
    src: templates/k8s/squid-service.json
    dest: /etc/squid-service.json

- name: compile tts cache pod config
  template:
    src: templates/k8s/tts_cache.json
    dest: /etc/tts_cache.json

- name: compile tts cache  service config
  template:
    src: templates/k8s/tts_cache-service.json
    dest: /etc/tts_cache-service.json

- name: compile wn pod config
  template:
    src: templates/k8s/wn.json
    dest: /etc/wn.json

- name: compile cvmfs pod config
  template:
    src: templates/k8s/cvmfs.json
    dest: /etc/cvmfs.json   

- name: create squid service
  command: kubectl apply -f /etc/squid-service.json

- name: create squid pod
  command: kubectl apply -f /etc/squid.json

- name: wait for cms squid to be up and running
  wait_for:
    host: "{{cms_config_mysquid_host}}"
    port: "{{cms_config_mysquid_port}}"
    delay: 20
    timeout: 600
    connect_timeout: 10

- name: create tts_cache service
  command: kubectl apply -f /etc/tts_cache-service.json

- name: create tts_cache pod
  command: kubectl apply -f /etc/tts_cache.json

- name: wait for cms proxy cache service to be up and running
  wait_for:
    host: "{{cms_config_proxycache_host}}"
    port: "{{cms_config_proxycache_serviceport}}"
    delay: 20
    timeout: 600
    connect_timeout: 10

- name: create wn pod
  command: kubectl apply -f /etc/wn.json

- name: create cvmfs pod
  command: kubectl apply -f /etc/cvmfs.json
