---

- name: start CMS squid
  run_once: true
  uri: 
     url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/cmssquid"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{ lookup('template', 'templates/cmssquid-app.json') }}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  changed_when: false
  tags:
    - cms_apps

- name: wait for cms squid to be up and running 
  wait_for: 
     host: "{{cms_config_mysquid_host}}" 
     port: "{{cms_config_mysquid_port}}"
     delay: 20
     timeout: 600
     connect_timeout: 10
  tags:
    - cms_apps

- name: start CMS proxy cache
  run_once: true
  uri: 
     url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/certcache"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{ lookup('template', 'templates/cmsproxycache-app.json') }}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  changed_when: false
  tags:
    - cms_apps

- name: wait for cms proxy cache service to be up and running 
  wait_for:
     host: "{{cms_config_proxycache_host}}"
     port: "{{cms_config_proxycache_serviceport}}"
     delay: 20
     timeout: 600
     connect_timeout: 10
  tags:
    - cms_apps

- name: start CMS cvmfs check
  run_once: true
  uri: 
     url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/cvmfscheck"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{ lookup('template', 'templates/cvmfskeepalive-app.json') }}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  changed_when: false
  tags:
    - cms_apps

- name: start CMS WN CentOS6
  run_once: true
  uri:
     url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/cmswn"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{ lookup('template', 'templates/cmswn-app.json') }}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  changed_when: false
  tags:
    - cms_apps

- name: start CMS WN CentOS7
  run_once: true
  uri:
     url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/cmswnel7"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{ lookup('template', 'templates/cmswnel7-app.json') }}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  changed_when: false
  tags:
    - cms_apps
